/// An ABI list parsed from a consolidated `abilists` file generated by [`glibc-abi-tool`].
///
/// [`glibc-abi-tool`]: https://github.com/ziglang/glibc-abi-tool/
#[derive(Debug)]
pub struct AbiList {}

/// An error case that may happen in [`AbiList::from_bytes`].
#[derive(Debug, thiserror::Error)]
pub enum AbiListParseError {
    #[error("provided byte slice was empty")]
    Empty,
}

impl AbiList {
    pub fn from_bytes(bytes: &'static [u8]) -> Result<Self, AbiListParseError> {
        if bytes.is_empty() {
            return Err(AbiListParseError::Empty);
        }

        Ok(AbiList {})
    }
}
